version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: hospital-backend_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata_hospital-backend:/var/lib/postgresql/data

volumes:
  pgdata_hospital-backend:
